---

- name: Manage Elastic Beats data shippers
  #  hosts: [ 'debops_service_elasticbeats' ]
  hosts: all
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops-contrib.elasticbeats
      tags: [ 'role::elasticbeats' ]
